name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Zeet Run
        uses: zeet-co/zeet-run-action@v0.0.2
        with:
          deploy_key: ${{ secrets.ZEET_DEPLOY_KEY }}
          project_id: a83b6e43-f8a9-42b2-8ed3-9e7c4ae8479b
          command: ls -al
          build: true

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zeetco/node-github-actions:latest

      - name: Zeet Deploy
        uses: zeet-co/zeet-deploy-action@v0.0.2
        with:
          deploy_key: ${{ secrets.ZEET_DEPLOY_KEY }}
          project_id: a83b6e43-f8a9-42b2-8ed3-9e7c4ae8479b
          image: zeetco/node-github-actions:latest
